---
defaultRules:
  create: false
global:
  rbac:
    create: false
alertmanager:
  enabled: false
grafana:
  enabled: false
kubeApiServer:
  enabled: false
kubelet:
  enabled: false
kubeControllerManager:
  enabled: false
coreDns:
  enabled: false
kubeDns:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
kubeStateMetrics:
  enabled: false
selfMonitor:
  enabled: false
nodeExporter:
  enabled: false
prometheusOperator:
  enabled: false
prometheus:
  enabled: false
thanosRuler:
  enabled: false
