prometheus:
  prometheusSpec:
    replicas: 1 # TODO: change to 2

    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    scrapeConfigSelectorNilUsesHelmValues: false

grafana:
  ingress:
    enabled: true
    hosts:
      - grafana.up42.abdalazizmoh.com
