apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-tenant
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  destination:
    name: in-cluster
    namespace: tenant-ns
  project: up42-apps
  source: null
  sources:
    - repoURL: https://operator.min.io/
      chart: tenant
      targetRevision: 7.1.1
      helm:
        releaseName: minio-tenant
        valueFiles:
          - $manifests/gitops/values/minio-tenant.yaml
    - ref: manifests
      repoURL: https://github.com/amohamedhey/up42-infra
      targetRevision: feat/enhance-task-doc-and-automation
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
