apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: s3www
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  destination:
    name: in-cluster
    namespace: s3www
  project: up42-apps
  source: null
  sources:
    - repoURL: https://github.com/amohamedhey/up42-infra.git
      path: helm/s3www
      targetRevision: master
      helm:
        releaseName: dev
        valueFiles:
          - $manifests/gitops/values/s3www.yaml
    - ref: manifests
      repoURL: https://github.com/amohamedhey/up42-infra
      targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
